# Generated by Django 6.0.5 on 2026-09-08 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='University Management System', max_length=120)),
                ('site_short_name', models.CharField(default='UMS', max_length=30)),
                ('topbar_text', models.CharField(blank=True, default='Welcome To University Management System', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cms/branding/')),
                ('contact_email', models.EmailField(blank=True, default='hello@example.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='0000', max_length=40)),
                ('contact_address', models.CharField(blank=True, default='Knowledge City, Campus Road', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('footer_blurb', models.TextField(blank=True, default='A modern, all-in-one platform to run admissions, academics, attendance, exams, fees and campus life — powered by built-in AI insights.')),
                ('footer_copyright', models.CharField(blank=True, default='University Management System · Built with Django · Powered by StackGee', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('file', models.ImageField(upload_to='cms/media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('layout', models.CharField(choices=[('landing', 'Landing page — full-bleed sections, no page header'), ('standard', 'Standard page — centred column with a page header'), ('wide', 'Wide page — full-width container, no page header')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('meta_description', models.CharField(blank=True, help_text='Shown by search engines under the page title.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('location', models.CharField(choices=[('header', 'Main header'), ('topbar', 'Top utility bar'), ('footer_explore', 'Footer — Explore'), ('footer_portals', 'Footer — Portals')], default='header', max_length=20)),
                ('url', models.CharField(blank=True, help_text='Used when no page is selected, e.g. /catalog/', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='cms.page')),
            ],
            options={
                'ordering': ['location', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero banner'), ('rich_text', 'Text section'), ('stats', 'Statistics strip'), ('features', 'Feature grid'), ('cards', 'Portal / link cards'), ('cta', 'Call to action'), ('image', 'Image / banner'), ('departments', 'Departments (live data)'), ('courses', 'Featured courses (live data)'), ('events', 'Upcoming events (live data)')], max_length=20)),
                ('variant', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/blocks/')),
                ('link_text', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('secondary_link_text', models.CharField(blank=True, max_length=80)),
                ('secondary_link_url', models.CharField(blank=True, max_length=300)),
                ('item_limit', models.PositiveSmallIntegerField(default=6)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
