# Generated by Django 6.0.5 on 2026-09-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_login_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEFERRED', 'Deferred'), ('ON_LEAVE', 'On Sick Leave'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='ACTIVE', max_length=15),
        ),
    ]
