# Generated by Django 6.0.5 on 2026-09-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
