# Generated by Django 6.0.5 on 2026-09-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_studentprofile_guardian_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['employee_id'], 'verbose_name': 'Teaching Staff', 'verbose_name_plural': 'Teaching Staff'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FACULTY', 'Teaching Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=10),
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/users/')),
                ('title', models.CharField(blank=True, default='', help_text='Official designation (e.g. Academic Registrar, Dean)', max_length=150)),
                ('department_or_office', models.CharField(blank=True, default='', help_text='Office/Faculty/Department (e.g. Office of the Registrar)', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Approved'), ('PENDING_VERIFICATION', 'Pending Verification'), ('INACTIVE', 'Inactive'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=25)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
            },
        ),
        migrations.CreateModel(
            name='UserSignatureHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('signature_image', models.ImageField(upload_to='signatures/users/history/')),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('department_or_office', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(max_length=25)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounts.usersignature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Signature History',
                'verbose_name_plural': 'User Signature Histories',
                'ordering': ['-version'],
            },
        ),
    ]
