# Generated by Django 6.0.5 on 2026-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_facultyprofile_options_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignature',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersignaturehistory',
            name='change_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
