# Generated by Django 6.0.5 on 2026-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_usersignature_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('FACULTY', 'Teaching Staff'), ('STUDENT', 'Student'), ('APPLICANT', 'Applicant')], default='STUDENT', max_length=15),
        ),
    ]
