# Generated by Django 6.0.5 on 2026-09-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_options_user_unique_lower_email'),
        ('university', '0049_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='university.cohort'),
        ),
    ]
