# Generated by Django 6.0.5 on 2026-09-13 17:36

from django.db import migrations


def populate_cohorts(apps, schema_editor):
    StudentProfile = apps.get_model('accounts', 'StudentProfile')
    Cohort = apps.get_model('university', 'Cohort')
    User = apps.get_model('accounts', 'User')

    for profile in StudentProfile.objects.all():
        cohort_name = "JAN-2026"
        if profile.admission_date:
            cohort_name = profile.admission_date.strftime("%b-%Y").upper()
        else:
            parts = (profile.roll_no or "").split("/")
            if len(parts) > 1 and parts[-1].isdigit() and len(parts[-1]) == 4:
                cohort_name = f"SEP-{parts[-1]}"
            elif profile.user_id:
                user = User.objects.get(pk=profile.user_id)
                if user.date_joined:
                    cohort_name = user.date_joined.strftime("%b-%Y").upper()

        cohort, _ = Cohort.objects.get_or_create(name=cohort_name)
        profile.cohort = cohort
        profile.save(update_fields=['cohort'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_studentprofile_cohort'),
        ('university', '0049_cohort'),
    ]

    operations = [
        migrations.RunPython(populate_cohorts, reverse_code=migrations.RunPython.noop),
    ]
