# Generated by Django 6.0.5 on 2026-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_preserve_existing_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Archived', 'Archived'), ('Upcoming', 'Upcoming')], default='Active', max_length=15),
        ),
    ]
