# Generated by Django 6.0.5 on 2026-09-08 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_login_activity'),
        ('university', '0004_course_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5, unique=True)),
                ('min_mark', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_mark', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('description', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-min_mark'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='cat_max_marks',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_max_marks',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='examiner_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exam',
            name='external_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_examined_exams', to='accounts.facultyprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='external_examiner_name',
            field=models.CharField(blank=True, default='', help_text='External examiner name and affiliation', max_length=150),
        ),
        migrations.AddField(
            model_name='exam',
            name='external_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='external_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_exam_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='internal_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_examined_exams', to='accounts.facultyprofile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='internal_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='internal_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_exam_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='cat_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='exam_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('MARKING', 'Marks entry'), ('INTERNAL_REVIEW', 'Internal review'), ('EXTERNAL_REVIEW', 'External review'), ('SUBMITTED', 'Awaiting approval'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
