# Generated by Django 6.0.5 on 2026-09-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_gradingscale_exam_cat_max_marks_exam_exam_max_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('TUTORIAL', 'Tutorial'), ('LAB', 'Lab / Practical'), ('SEMINAR', 'Seminar')], default='LECTURE', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_schedules', to='university.examroom')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='university.academicterm')),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='schedule_end_after_start')],
            },
        ),
    ]
