# Generated by Django 6.0.5 on 2026-09-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
