# Generated by Django 6.0.5 on 2026-09-08 13:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_login_activity'),
        ('university', '0008_alter_enrollment_status_semesterregistration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('academic_year', models.CharField(default='2026/2027', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('national_id', models.CharField(max_length=50, verbose_name='National ID / Passport No.')),
                ('address', models.TextField(blank=True, default='')),
                ('secondary_school', models.CharField(blank=True, default='', max_length=160)),
                ('kcse_index_number', models.CharField(blank=True, default='', max_length=60)),
                ('kcse_mean_grade', models.CharField(blank=True, default='C+', max_length=10)),
                ('kcse_year', models.PositiveIntegerField(default=2025)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted (Admitted)'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled / Matriculated')], db_index=True, default='SUBMITTED', max_length=20)),
                ('admitted_reg_no', models.CharField(blank=True, default='', max_length=50)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='university.program')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_application', to='accounts.studentprofile')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='university.intake')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=45000.0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('examination_fee', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('library_fee', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('activity_fee', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('medical_fee', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('ict_fee', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('student_union_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='university.program')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_structures', to='university.academicterm')),
            ],
            options={
                'ordering': ['program', 'year_of_study', 'semester'],
                'unique_together': {('program', 'term', 'year_of_study', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SupplementaryExamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('SUPPLEMENTARY', 'Supplementary Examination'), ('SPECIAL', 'Special Examination')], default='SUPPLEMENTARY', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_registrations', to='university.course')),
                ('fee_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.feeinvoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_registrations', to='accounts.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course', 'term', 'exam_type')},
            },
        ),
    ]
