# Generated by Django 6.0.5 on 2026-09-08 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_intake_application_feestructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_display', models.CharField(blank=True, default='System', max_length=150)),
                ('user_role', models.CharField(blank=True, default='Anonymous', max_length=30)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified')], db_index=True, max_length=30)),
                ('module', models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Faculty'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Departments', 'Departments'), ('Academics', 'Academics & Registrations'), ('Examinations', 'Examinations & Marks'), ('Fees', 'Fees & Finance'), ('Admissions', 'Admissions & Applications'), ('Timetable', 'Timetable'), ('Security & Auth', 'Security & Authentication'), ('System Configuration', 'System Configuration'), ('Notices & Events', 'Notices & Events')], db_index=True, max_length=40)),
                ('entity', models.CharField(blank=True, default='', max_length=80)),
                ('entity_id', models.CharField(blank=True, default='', max_length=60)),
                ('description', models.TextField()),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(default='Desktop', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecycleBinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('module', models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Faculty'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Departments', 'Departments'), ('Timetable', 'Timetable Schedules'), ('Fees', 'Fee Invoices & Structures'), ('Admissions', 'Admissions & Applications'), ('Notices', 'Campus Notices'), ('Events', 'Campus Events'), ('Examinations', 'Examinations & Marks'), ('Other', 'Other Records')], db_index=True, default='Other', max_length=40)),
                ('serialized_data', models.JSONField(help_text='Complete JSON snapshot of model fields and relationships')),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(default='Desktop', max_length=30)),
                ('is_restored', models.BooleanField(db_index=True, default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False, help_text='Protected academic/final records requiring superuser to purge')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_recycle_items', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_recycle_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Setup'), ('UNIVERSITY', 'University Structure & Info'), ('EXAMINATION', 'Course & Examination Setup'), ('TIMETABLE', 'Timetable Setup'), ('REGISTRATION', 'Student & Registration Setup'), ('FINANCE', 'Finance & Fees Setup'), ('SECURITY', 'User & Security Setup')], db_index=True, max_length=30)),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('value_type', models.CharField(choices=[('STRING', 'Text String'), ('INTEGER', 'Integer Number'), ('DECIMAL', 'Decimal Number'), ('BOOLEAN', 'Boolean (True/False)'), ('JSON', 'Structured JSON')], default='STRING', max_length=20)),
                ('value', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
