# Generated by Django 6.0.5 on 2026-09-08 14:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_login_activity'),
        ('university', '0010_auditlog_recyclebinitem_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, default='', max_length=30)),
                ('category', models.CharField(default='Computer Science', max_length=100)),
                ('call_number', models.CharField(blank=True, default='', max_length=50)),
                ('publisher', models.CharField(blank=True, default='', max_length=150)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('shelf_location', models.CharField(default='Stack 3, Shelf B', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GraduationCeremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025/2026', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('ceremony_date', models.DateField()),
                ('venue', models.CharField(default='Main University Pavilion', max_length=150)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('SENATE_APPROVED', 'Senate Approved'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=25)),
                ('chief_guest', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Graduation Ceremonies',
                'ordering': ['-ceremony_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('campus', models.CharField(default='Main Campus', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male Students Only'), ('FEMALE', 'Female Students Only'), ('MIXED', 'Co-educational')], default='MIXED', max_length=20)),
                ('warden_name', models.CharField(blank=True, default='Hostel Warden', max_length=100)),
                ('warden_phone', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Loan'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='ACTIVE', max_length=20)),
                ('fine_accrued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('fine_paid', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='university.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_loans', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='GraduationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('total_credits_earned', models.IntegerField(default=0)),
                ('final_cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('classification', models.CharField(choices=[('FIRST_CLASS', 'First Class Honours'), ('SECOND_UPPER', 'Second Class Honours (Upper Division)'), ('SECOND_LOWER', 'Second Class Honours (Lower Division)'), ('PASS', 'Pass'), ('NOT_APPLICABLE', 'Not Applicable')], default='SECOND_UPPER', max_length=30)),
                ('certificate_serial', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Application Submitted'), ('CLEARANCE_IN_PROGRESS', 'Clearance in Progress'), ('CLEARED', 'Fully Cleared'), ('SENATE_APPROVED', 'Senate Approved'), ('GRADUATED', 'Conferred / Graduated'), ('REJECTED', 'Rejected / On Academic Hold')], default='APPLIED', max_length=30)),
                ('senate_approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_record', to='accounts.studentprofile')),
                ('ceremony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduands', to='university.graduationceremony')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('floor', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Occupancy'), ('QUAD', 'Quad (4-Beds)')], default='DOUBLE', max_length=20)),
                ('capacity', models.IntegerField(default=2)),
                ('occupied_beds', models.IntegerField(default=0)),
                ('fee_per_semester', models.DecimalField(decimal_places=2, default=Decimal('8000.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='university.hostelblock')),
            ],
            options={
                'ordering': ['block', 'room_number'],
                'unique_together': {('block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('ALLOCATED', 'Allocated'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], default='APPLIED', max_length=20)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('room_key_number', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='accounts.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicterm')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='university.hostelroom')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='PastExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('MAIN', 'Main University Exam'), ('CAT', 'Continuous Assessment Test'), ('SUPPLEMENTARY', 'Supplementary / Special Exam')], default='MAIN', max_length=20)),
                ('academic_year', models.CharField(default='2024/2025', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='past_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='university.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.academicterm')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('FINANCE', 'Finance Office'), ('LIBRARY', 'University Library'), ('ACADEMIC_DEAN', 'Academic Dean / HOD'), ('STUDENT_AFFAIRS', 'Hostel & Student Affairs'), ('REGISTRAR', 'Academic Registrar')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CLEARED', 'Cleared'), ('REJECTED', 'Hold / Uncleared')], default='PENDING', max_length=20)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearances', to='university.graduationapplication')),
            ],
            options={
                'ordering': ['department'],
                'unique_together': {('application', 'department')},
            },
        ),
    ]
