# Generated by Django 6.0.5 on 2026-09-08 14:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_login_activity'),
        ('university', '0011_book_graduationceremony_hostelblock_bookloan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('company_branch_location', models.CharField(default='Headquarters', max_length=150)),
                ('company_address', models.TextField(blank=True)),
                ('company_supervisor_name', models.CharField(max_length=100)),
                ('company_supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('company_supervisor_phone', models.CharField(max_length=30)),
                ('department_or_unit', models.CharField(default='IT / Operations', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('intro_letter_reference', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='attachments/offers/')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_attachments', to='accounts.facultyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicterm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now)),
                ('organization_suitability_score', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('student_attendance_score', models.DecimalField(decimal_places=2, default=Decimal('13.00'), max_digits=5)),
                ('technical_skills_score', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('logbook_maintenance_score', models.DecimalField(decimal_places=2, default=Decimal('17.00'), max_digits=5)),
                ('oral_presentation_score', models.DecimalField(decimal_places=2, default=Decimal('17.00'), max_digits=5)),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5)),
                ('grade', models.CharField(default='A', max_length=5)),
                ('assessor_comments', models.TextField(blank=True)),
                ('industry_supervisor_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_assessments', to='accounts.facultyprofile')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='university.attachmentplacement')),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentLogbookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('activities_summary', models.TextField()),
                ('skills_acquired', models.TextField()),
                ('challenges_encountered', models.TextField(blank=True)),
                ('company_supervisor_signed', models.BooleanField(default=False)),
                ('faculty_supervisor_reviewed', models.BooleanField(default=False)),
                ('faculty_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to='university.attachmentplacement')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('attachment', 'week_number')},
            },
        ),
    ]
