# Generated by Django 6.0.5 on 2026-09-08 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_status'),
        ('university', '0014_systempermission_staffrole_staffroleassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('DEFERMENT', 'Deferment'), ('WITHDRAWAL', 'Withdrawal'), ('SICK_LEAVE', 'Sick Leave')], max_length=15)),
                ('reason', models.TextField()),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='student_requests/%Y/%m/')),
                ('start_date', models.DateField(blank=True, help_text='Deferment / leave start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expected deferment / leave end date (resumption date)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=15)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_comments', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('student',), name='one_pending_request_per_student')],
            },
        ),
    ]
