# Generated by Django 6.0.5 on 2026-09-08 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0015_studentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CARD', 'Debit / Credit Card'), ('BANK', 'Bank Transfer')], default='MPESA', max_length=10)),
                ('reference', models.CharField(help_text='Transaction / reference number from the payment channel', max_length=60)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=15)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='university.application')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
