# Generated by Django 6.0.5 on 2026-09-09 04:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_applicationfeepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentReleaseControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('transcript_official', 'Official Academic Transcript'), ('transcript_provisional', 'Provisional Transcript'), ('exam_card', 'Examination Card'), ('results_statement', 'Statement of Results'), ('progress_report', 'Progressive Academic Report')], help_text='The category of document governed by this control.', max_length=32)),
                ('is_open', models.BooleanField(default=True, help_text='Master toggle to immediately permit or block student access/downloads.')),
                ('open_date', models.DateTimeField(blank=True, help_text='Date and time when downloads automatically become available to students.', null=True)),
                ('lock_date', models.DateTimeField(blank=True, help_text='Date and time when downloads automatically lock / expire.', null=True)),
                ('require_financial_clearance', models.BooleanField(default=False, help_text='Require student to have no outstanding fee balance beyond the allowed threshold.')),
                ('max_allowed_fee_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum outstanding balance (KES) allowed before document is locked.', max_digits=12)),
                ('require_senate_approval', models.BooleanField(default=False, help_text='Require results to be Senate-approved before opening this document.')),
                ('notes', models.CharField(blank=True, default='', help_text='Custom message displayed to students when access is locked.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(blank=True, help_text='Academic term this control applies to (leave empty for universal policy).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_controls', to='university.academicterm')),
            ],
            options={
                'ordering': ['document_type', '-term__start_date'],
                'unique_together': {('term', 'document_type')},
            },
        ),
    ]
