# Generated by Django 6.0.5 on 2026-09-09 04:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_documentreleasecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('dean_name', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculty / School',
                'verbose_name_plural': 'Faculties & Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='award_title',
            field=models.CharField(blank=True, default='', help_text='Official designation awarded upon completion (e.g. Bachelor of Science in Computer Science)', max_length=160),
        ),
        migrations.AddField(
            model_name='program',
            name='career_prospects',
            field=models.TextField(blank=True, default='', help_text='Career prospects and learning outcomes'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_unit',
            field=models.CharField(choices=[('Years', 'Years'), ('Semesters', 'Semesters'), ('Trimesters', 'Trimesters'), ('Months', 'Months')], default='Years', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='duration_value',
            field=models.PositiveSmallIntegerField(default=4, help_text='Duration in specified units'),
        ),
        migrations.AddField(
            model_name='program',
            name='max_credits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_credits',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('Degree', 'University Bachelor Degree'), ('Diploma', 'TVET / Higher National Diploma'), ('Certificate', 'TVET / Professional Certificate'), ('Masters', "Master's Degree"), ('Doctorate', 'Doctor of Philosophy / Ph.D.'), ('PostgradDip', 'Postgraduate Diploma')], default='Degree', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='semesters_per_year',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('Active', 'Active & Admitting'), ('Inactive', 'Inactive / Suspended'), ('Phased Out', 'Phased Out / Teach-Out Only')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='study_mode',
            field=models.CharField(choices=[('Full-Time', 'Full-Time Regular'), ('Part-Time', 'Part-Time'), ('Evening', 'Evening Classes'), ('Weekend', 'Weekend Intensive'), ('Online', 'Distance / E-Learning')], default='Full-Time', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='total_semesters',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_years',
            field=models.PositiveSmallIntegerField(default=4, help_text='Duration in years (for backward compatibility)'),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('CERT', 'Certificate'), ('DIP', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('MS', "Master's"), ('PHD', 'Doctorate')], default='UG', max_length=6),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Faculty or School this department belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='university.school', verbose_name='Faculty / School'),
        ),
    ]
