# Generated by Django 6.0.5 on 2026-09-09 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_school_program_award_title_program_career_prospects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Semester / Term', 'verbose_name_plural': 'Academic Semesters & Terms'},
        ),
        migrations.AddField(
            model_name='academicterm',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='exam_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='exam_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='semester_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='e.g. 1, 2, 3'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CURRENT', 'Current'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='term_type',
            field=models.CharField(choices=[('SEMESTER', 'Semester'), ('TRIMESTER', 'Trimester'), ('TERM', 'Term'), ('SUMMER', 'Summer / Special Session')], default='SEMESTER', max_length=20),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified'), ('PUBLISH', 'Record Published'), ('UNPUBLISH', 'Record Unpublished'), ('CLOSE', 'Academic Period Closed'), ('REOPEN', 'Academic Period Reopened'), ('SET_CURRENT', 'Set as Current / Active')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Faculty'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Departments', 'Departments'), ('Academics', 'Academics & Registrations'), ('Academic Calendar', 'Academic Years & Semesters'), ('Examinations', 'Examinations & Marks'), ('Fees', 'Fees & Finance'), ('Admissions', 'Admissions & Applications'), ('Timetable', 'Timetable'), ('Security & Auth', 'Security & Authentication'), ('System Configuration', 'System Configuration'), ('Notices & Events', 'Notices & Events')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2026/2027', max_length=30, unique=True)),
                ('code', models.CharField(blank=True, help_text='e.g. AY-2026-2027', max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CURRENT', 'Current'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_no', models.CharField(blank=True, default='', help_text='Institutional reference / Gazette notice', max_length=60)),
                ('max_programmes_allowed', models.PositiveIntegerField(default=1, help_text='Max concurrent programmes a student can accept')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_academic_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='academicterm',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='university.academicyear'),
        ),
    ]
