# Generated by Django 6.0.5 on 2026-09-09 13:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_status'),
        ('university', '0021_intake_academic_year_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text="Identifier used in templates e.g. 'campus'", max_length=60, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text'), ('SELECT', 'Dropdown Select'), ('CHECKBOX', 'Yes / No Checkbox'), ('NUMBER', 'Number')], default='TEXT', max_length=20)),
                ('choices_list', models.TextField(blank=True, default='', help_text="Comma-separated choices for dropdowns e.g. 'Main Campus, Nairobi CBD, Mombasa'")),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified'), ('PUBLISH', 'Record Published'), ('UNPUBLISH', 'Record Unpublished'), ('CLOSE', 'Academic Period Closed'), ('REOPEN', 'Academic Period Reopened'), ('SET_CURRENT', 'Set as Current / Active'), ('GENERATE_DOCUMENT', 'Document Generated'), ('REGENERATE_DOCUMENT', 'Document Regenerated'), ('RESEND_DOCUMENT', 'Document Resent'), ('VERIFY_DOCUMENT', 'Document Verified'), ('REVOKE_DOCUMENT', 'Document Revoked')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='documentreleasecontrol',
            name='document_type',
            field=models.CharField(choices=[('transcript_official', 'Official Academic Transcript'), ('transcript_provisional', 'Provisional Transcript'), ('exam_card', 'Examination Card'), ('results_statement', 'Statement of Results'), ('progress_report', 'Progressive Academic Report'), ('admission_letter', 'Official Admission Letter'), ('application_docs', 'Application & Admission Documents')], help_text='The category of document governed by this control.', max_length=32),
        ),
        migrations.CreateModel(
            name='AdmissionDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name e.g. 'Standard Undergraduate Admission Letter'", max_length=160)),
                ('document_type', models.CharField(choices=[('ADMISSION_LETTER', 'Official Admission Letter'), ('PROVISIONAL_OFFER', 'Provisional Letter of Offer'), ('ACCEPTANCE_FORM', 'Acceptance of Offer Form'), ('CALLING_LETTER', 'Reporting & Calling Letter')], default='ADMISSION_LETTER', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default template for this document type')),
                ('version', models.PositiveIntegerField(default=1)),
                ('header_title', models.CharField(default='OFFICE OF THE REGISTRAR (ACADEMIC AFFAIRS)', max_length=255)),
                ('salutation_template', models.CharField(default='Dear {{student_name}},', max_length=255)),
                ('subject_template', models.CharField(default='ADMISSION TO THE {{programme_name}} ({{programme_code}})', max_length=255)),
                ('body_template', models.TextField(default='I am pleased to inform you that you have been offered admission to the {{programme_name}} in the {{faculty_name}} for the {{academic_year}} Academic Year commencing in {{semester}}.\n\nYou are required to report to the university on {{reporting_date}} for orientation, registration and fee payment verification.')),
                ('terms_and_conditions', models.TextField(blank=True, default='1. This offer of admission is subject to verification of your original academic and identification certificates.\n2. All university fees must be paid in full or in approved installments prior to course registration.\n3. University rules, regulations and academic policies apply at all times.')),
                ('fee_schedule_instructions', models.TextField(blank=True, default='Tuition and statutory fees must be deposited to the University Bank Account (Absa Bank, Acc No. 0451234567, Westlands Branch) or via M-Pesa Paybill 522522 with your Application/Student Number as reference.')),
                ('signatory_name', models.CharField(default='Dr. Margaret Omolo, PhD', max_length=120)),
                ('signatory_title', models.CharField(default='Registrar, Academic & Student Affairs', max_length=120)),
                ('signatory_signature', models.ImageField(blank=True, null=True, upload_to='admissions/signatures/')),
                ('official_seal', models.ImageField(blank=True, null=True, upload_to='admissions/seals/')),
                ('verification_base_url', models.CharField(default='https://ums.ac.ke/verify-admission/', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, help_text='Applicable academic year (leave blank for universal default)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='Specific programme (leave blank for all programmes)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.program')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('KCSE_CERTIFICATE', 'KCSE Certificate / Result Slip'), ('NATIONAL_ID', 'National ID / Birth Certificate / Passport'), ('PASSPORT_PHOTO', 'Passport Size Photograph'), ('LEAVING_CERTIFICATE', 'School Leaving Certificate'), ('TRANSCRIPT', 'Previous Academic Transcript'), ('SPONSOR_LETTER', 'Sponsorship / Financial Guarantee'), ('MEDICAL_REPORT', 'Medical Examination Report'), ('OTHER', 'Other Supporting Document')], default='OTHER', max_length=40)),
                ('name', models.CharField(help_text="Display title e.g. 'KCSE Result Slip'", max_length=200)),
                ('file', models.FileField(upload_to='applications/attachments/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, default='application/pdf', max_length=100)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Approved'), ('REJECTED', 'Rejected / Incomplete'), ('FLAGGED', 'Flagged for Investigation')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('is_visible_to_student', models.BooleanField(default=True, help_text='Permit student to view/download this file in portal')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='university.application')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuedAdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ADMISSION_LETTER', 'Official Admission Letter'), ('PROVISIONAL_OFFER', 'Provisional Letter of Offer'), ('ACCEPTANCE_FORM', 'Acceptance of Offer Form'), ('CALLING_LETTER', 'Reporting & Calling Letter')], default='ADMISSION_LETTER', max_length=40)),
                ('document_reference', models.CharField(db_index=True, max_length=80, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CURRENT', 'Current Active Version'), ('SUPERSEDED', 'Superseded by Newer Version'), ('REVOKED', 'Revoked / Voided')], db_index=True, default='CURRENT', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('rendered_context', models.JSONField(blank=True, default=dict, help_text='Snapshot of all evaluation tokens at time of issue')),
                ('rendered_content', models.TextField(blank=True, default='', help_text='Rendered text content')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='admissions/issued_letters/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_reason', models.CharField(blank=True, default='', help_text='Reason for generation or regeneration', max_length=255)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('is_current_version', models.BooleanField(db_index=True, default=True)),
                ('is_visible_to_student', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicyear')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_documents', to='university.application')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_admission_documents', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_admission_documents', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicterm')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_documents', to='accounts.studentprofile')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='university.admissiondocumenttemplate')),
            ],
            options={
                'ordering': ['-version', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('EMAIL', 'Email Transmission'), ('SMS', 'SMS Notification'), ('PORTAL_NOTICE', 'Student Portal Notification')], default='EMAIL', max_length=20)),
                ('recipient', models.CharField(help_text='Email address, phone number, or student ID', max_length=160)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message_body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SENT', 'Sent Successfully'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_document_deliveries', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='university.issuedadmissiondocument')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='university.application')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_values', to='university.applicationcustomfield')),
            ],
            options={
                'unique_together': {('application', 'field')},
            },
        ),
    ]
