# Generated by Django 6.0.5 on 2026-09-09 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0022_applicationcustomfield_alter_auditlog_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified'), ('PUBLISH', 'Record Published'), ('UNPUBLISH', 'Record Unpublished'), ('CLOSE', 'Academic Period Closed'), ('REOPEN', 'Academic Period Reopened'), ('SET_CURRENT', 'Set as Current / Active'), ('GENERATE_DOCUMENT', 'Document Generated'), ('REGENERATE_DOCUMENT', 'Document Regenerated'), ('RESEND_DOCUMENT', 'Document Resent'), ('VERIFY_DOCUMENT', 'Document Verified'), ('REVOKE_DOCUMENT', 'Document Revoked'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled'), ('MODULE_STATUS_CHANGE', 'Module Status Changed'), ('SUBMODULE_STATUS_CHANGE', 'Submodule Status Changed'), ('FEATURE_STATUS_CHANGE', 'Feature Status Changed'), ('MODULES_BULK_UPDATE', 'Modules Bulk Status Updated')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Faculty'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Departments', 'Departments'), ('Academics', 'Academics & Registrations'), ('Academic Calendar', 'Academic Years & Semesters'), ('Examinations', 'Examinations & Marks'), ('Fees', 'Fees & Finance'), ('Admissions', 'Admissions & Applications'), ('Timetable', 'Timetable'), ('Security & Auth', 'Security & Authentication'), ('System Configuration', 'System Configuration'), ('Notices & Events', 'Notices & Events'), ('Module Management', 'Module Management')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique machine identifier e.g. 'examinations', 'finance'", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='Academic', help_text="Grouping e.g. 'Academic', 'Administrative', 'Finance', 'Student Services', 'Governance & Security'", max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-solid fa-cube', help_text="FontAwesome icon class e.g. 'fa-solid fa-file-pen'", max_length=60)),
                ('status', models.CharField(choices=[('ENABLED', 'Active / Enabled'), ('MAINTENANCE', 'Under Maintenance'), ('COMING_SOON', 'Coming Soon...'), ('DISABLED', 'Disabled / Inactive')], db_index=True, default='ENABLED', max_length=20)),
                ('status_message', models.TextField(blank=True, default='', help_text='Custom message displayed to users when inactive, under maintenance, or coming soon')),
                ('is_critical', models.BooleanField(default=False, help_text='Protected core system module that cannot be disabled (e.g. Auth, System Admin)')),
                ('sort_order', models.IntegerField(default=0)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text="List of target user roles allowed access (e.g. ['ADMIN', 'FACULTY', 'STUDENT']) or empty for all")),
                ('route_prefixes', models.JSONField(blank=True, default=list, help_text='List of URL namespaces or path prefixes associated with this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSubmodule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique machine identifier e.g. 'unit_registration', 'marks_entry'", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='fa-solid fa-circle-dot', max_length=60)),
                ('status', models.CharField(choices=[('ENABLED', 'Active / Enabled'), ('MAINTENANCE', 'Under Maintenance'), ('COMING_SOON', 'Coming Soon...'), ('DISABLED', 'Disabled / Inactive')], db_index=True, default='ENABLED', max_length=20)),
                ('status_message', models.TextField(blank=True, default='')),
                ('is_critical', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('route_names', models.JSONField(blank=True, default=list, help_text="List of Django url_names (e.g. ['admin_unit_registrations', 'student_register_units'])")),
                ('path_patterns', models.JSONField(blank=True, default=list, help_text="Path prefixes (e.g. ['/academics/register/', '/manage/academics/registrations/'])")),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='university.systemmodule')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Submodule',
                'verbose_name_plural': 'System Submodules',
                'ordering': ['module', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Unique machine identifier e.g. 'deferment', 'sick_leave', 'publish_results'", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ENABLED', 'Active / Enabled'), ('MAINTENANCE', 'Under Maintenance'), ('COMING_SOON', 'Coming Soon...'), ('DISABLED', 'Disabled / Inactive')], db_index=True, default='ENABLED', max_length=20)),
                ('status_message', models.TextField(blank=True, default='')),
                ('is_critical', models.BooleanField(default=False)),
                ('action_code', models.CharField(blank=True, default='', help_text="Optional identifier checked in views/services e.g. 'DEFERMENT'", max_length=60)),
                ('route_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='university.systemsubmodule')),
            ],
            options={
                'verbose_name': 'System Feature',
                'verbose_name_plural': 'System Features',
                'ordering': ['submodule', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(choices=[('REQUIRED', 'Strict Prerequisite (Required)'), ('RECOMMENDED', 'Recommended Dependency')], default='REQUIRED', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_source', to='university.systemmodule')),
                ('target_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_as_target', to='university.systemmodule')),
            ],
            options={
                'verbose_name': 'Module Dependency',
                'verbose_name_plural': 'Module Dependencies',
                'unique_together': {('source_module', 'target_module')},
            },
        ),
    ]
