# Generated by Django 6.0.5 on 2026-09-09 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_alter_auditlog_action_alter_auditlog_module_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlHeartbeat',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_success_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='departments',
            field=models.ManyToManyField(blank=True, to='university.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='ends_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notice',
            name='message_type',
            field=models.CharField(choices=[('INFORMATION', 'Information'), ('ANNOUNCEMENT', 'Announcement'), ('WARNING', 'Warning'), ('MAINTENANCE', 'Maintenance'), ('EMERGENCY', 'Emergency'), ('SUCCESS', 'Success'), ('IMPORTANT_NOTICE', 'Important Notice')], default='INFORMATION', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='modules',
            field=models.ManyToManyField(blank=True, to='university.systemmodule'),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='programmes',
            field=models.ManyToManyField(blank=True, to='university.program'),
        ),
        migrations.AddField(
            model_name='notice',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='targeted_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], db_index=True, default='PUBLISHED', max_length=12),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='university.staffrole'),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.messagetemplate'),
        ),
        migrations.CreateModel(
            name='SystemRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('EMERGENCY_MAINTENANCE', 'Emergency maintenance'), ('MODULE', 'Module lockdown'), ('ROLE', 'Role lockdown'), ('READ_ONLY', 'Read only'), ('LOCKDOWN', 'Full lockdown'), ('EMERGENCY', 'Emergency lockdown')], max_length=24)),
                ('reason', models.TextField(help_text='Internal reason; visible only to authorized administrators.')),
                ('public_message', models.TextField(default='The system is temporarily unavailable. Please try again later.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=12)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('time_zone', models.CharField(default='Africa/Nairobi', max_length=64)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('allow_bypass', models.BooleanField(default=True, help_text='Allow explicitly permitted bypass users. Incident managers always retain recovery access.')),
                ('session_policy', models.CharField(choices=[('BLOCK', 'Block requests'), ('LOGOUT', 'Force logout'), ('READ_ONLY', 'Existing sessions read only')], default='BLOCK', max_length=20)),
                ('warning_minutes', models.JSONField(blank=True, default=list)),
                ('notification_message', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('affected_user_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(blank=True, to='university.systemfeature')),
                ('modules', models.ManyToManyField(blank=True, to='university.systemmodule')),
                ('submodules', models.ManyToManyField(blank=True, to='university.systemsubmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.notice')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university.systemrestriction')),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.systemrestriction'),
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='IN_APP', max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='university.notice')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'recipient', 'method'), name='unique_system_message_delivery')],
            },
        ),
        migrations.AddConstraint(
            model_name='systemrestriction',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='restriction_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='controlnotification',
            constraint=models.UniqueConstraint(fields=('restriction', 'event'), name='unique_control_notification'),
        ),
    ]
