# Generated by Django 6.0.5 on 2026-09-09 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_status'),
        ('university', '0025_system_control_catalog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', '-paid_on']},
        ),
        migrations.AddField(
            model_name='payment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicyear'),
        ),
        migrations.AddField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='internal_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_callback_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending Confirmation'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], db_index=True, default='SUCCESSFUL', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.academicterm'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='university.feeinvoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Online', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, default='TXN-0000', max_length=64),
        ),
        migrations.CreateModel(
            name='FeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable account label e.g. Main Tuition M-Pesa Paybill', max_length=120)),
                ('account_type', models.CharField(choices=[('MPESA_PAYBILL', 'M-Pesa Paybill'), ('MPESA_TILL', 'M-Pesa Buy Goods / Till'), ('CARD_GATEWAY', 'Card Payment Gateway'), ('BANK_ACCOUNT', 'Bank Account Transfer'), ('OTHER', 'Other Payment Channel')], db_index=True, default='MPESA_PAYBILL', max_length=30)),
                ('provider', models.CharField(choices=[('SAFARICOM', 'Safaricom M-Pesa'), ('STRIPE', 'Stripe'), ('PESAPAL', 'Pesapal'), ('EQUITY', 'Equity Bank'), ('KCB', 'KCB Bank'), ('COOP', 'Co-operative Bank'), ('STANDARD_CHARTERED', 'Standard Chartered'), ('GENERIC', 'Generic Payment Gateway')], default='SAFARICOM', max_length=40)),
                ('account_identifier', models.CharField(help_text='Paybill Number, Till Number, Merchant ID, or Bank Account Number', max_length=80)),
                ('account_name', models.CharField(blank=True, default='', help_text='Business name, paybill account name, or bank account title', max_length=120)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('environment', models.CharField(choices=[('SANDBOX', 'Sandbox / Test'), ('PRODUCTION', 'Production / Live')], default='SANDBOX', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Default account for this payment type')),
                ('supported_methods', models.JSONField(blank=True, default=list, help_text="List of supported methods e.g. ['MPESA_PAYBILL'], ['VISA', 'MASTERCARD']")),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='Public configuration such as callback URL, confirmation URL, branch, bank code')),
                ('encrypted_credentials', models.TextField(blank=True, default='', help_text='Encrypted API keys, consumer secrets, passkeys')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, default='', max_length=40)),
                ('last_test_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_accounts', to='university.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_accounts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_accounts', to='university.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_accounts', to='university.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fee_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='university.feeaccount'),
        ),
        migrations.CreateModel(
            name='FeeAccountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TEST_CONNECTION', 'Connection Test'), ('INITIATE_PAYMENT', 'Payment Initiated'), ('CALLBACK_RECEIVED', 'Callback Received'), ('VERIFICATION', 'Payment Verification'), ('ERROR', 'Provider Error'), ('CONFIG_CHANGE', 'Configuration Change')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('payload_preview', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fee_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='university.feeaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipt', to='university.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_receipts', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allocated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='university.feeinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='university.payment')),
            ],
            options={
                'ordering': ['-allocated_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_reference', models.CharField(db_index=True, max_length=100)),
                ('internal_reference', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DUPLICATE', 'Duplicate Transaction'), ('REQUIRES_REVIEW', 'Requires Review')], db_index=True, default='UNMATCHED', max_length=30)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reconciled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('fee_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='university.feeaccount')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to='university.payment')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reversal_type', models.CharField(choices=[('REVERSAL', 'Full Reversal'), ('REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund')], default='REVERSAL', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('provider_reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved & Applied'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reversals', to=settings.AUTH_USER_MODEL)),
                ('original_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='university.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_reversals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
