# Generated by Django 6.0.5 on 2026-09-09 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0027_backupretentionpolicy_backupstorage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('template_code', models.CharField(blank=True, default='', max_length=60)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='SENT', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('kind', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff / Faculty'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], default='STUDENT', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('FAILED', 'Provisioning Failed'), ('SUSPENDED', 'Suspended'), ('DISABLED', 'Disabled'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=15)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('provider_message', models.TextField(blank=True, default='')),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutional_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password history entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('purpose', models.CharField(choices=[('RESET', 'Password Reset'), ('ACTIVATION', 'Account Activation'), ('ADMIN_RESET', 'Administrator-Initiated Reset')], default='RESET', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff / Faculty'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], db_index=True, default='STUDENT', max_length=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending Activation'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('DISABLED', 'Disabled'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=15)),
                ('status_reason', models.CharField(blank=True, default='', max_length=255)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('last_failed_login_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, default='', max_length=255)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_method', models.CharField(blank=True, default='', help_text='e.g. TOTP, EMAIL, SMS — reserved for future MFA rollout.', max_length=30)),
                ('campus', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff / Faculty'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], default='STAFF', max_length=15)),
                ('color', models.CharField(default='#6C5CE7', max_length=20)),
                ('icon', models.CharField(default='fa-solid fa-users-rectangle', max_length=60)),
                ('precedence', models.PositiveSmallIntegerField(default=100, help_text='Lower value = higher priority when groups conflict.')),
                ('is_system_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='user_groups', to='university.systempermission')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_groups', to='university.staffrole')),
            ],
            options={
                'ordering': ['precedence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('STUDENT', 'Student'), ('STAFF', 'Staff / Faculty'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], default='STUDENT', max_length=15)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PREVIEW', 'Previewed'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Completed With Errors'), ('FAILED', 'Failed')], default='PREVIEW', max_length=12)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempted', models.CharField(db_index=True, max_length=150)),
                ('user_type', models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('STAFF', 'Staff / Faculty'), ('ADMIN', 'Administrator'), ('OTHER', 'Other')], default='', max_length=15)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, choices=[('BAD_CREDENTIALS', 'Invalid username or password'), ('INACTIVE', 'Account not active'), ('LOCKED', 'Account locked'), ('SUSPENDED', 'Account suspended'), ('DISABLED', 'Account disabled'), ('EXPIRED', 'Account expired'), ('UNKNOWN_USER', 'No such account'), ('BLOCKED', 'Blocked by system control')], default='', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('device_type', models.CharField(blank=True, default='', max_length=30)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('mfa_used', models.BooleanField(default=False)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-login_at'],
                'indexes': [models.Index(fields=['-login_at', 'success'], name='university__login_a_176748_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='university.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group__precedence', 'group__name'],
                'unique_together': {('user', 'group')},
            },
        ),
    ]
