# Generated by Django 6.0.5 on 2026-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0028_emaildeliveryrecord_institutionalemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclebinitem',
            name='module',
            field=models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Faculty'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Schools', 'Schools & Faculties'), ('Departments', 'Departments'), ('Timetable', 'Timetable Schedules'), ('Fees', 'Fee Invoices & Structures'), ('Admissions', 'Admissions & Applications'), ('Notices', 'Campus Notices'), ('Events', 'Campus Events'), ('Examinations', 'Examinations & Marks'), ('Calendar', 'Academic Calendar & Terms'), ('Other', 'Other Records')], db_index=True, default='Other', max_length=40),
        ),
    ]
