# Generated by Django 6.0.5 on 2026-09-10 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0029_alter_recyclebinitem_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoLiveIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUNCTIONAL_TESTING', 'Functional Testing'), ('UI_UX', 'UI/UX Quality'), ('ACCESSIBILITY', 'Accessibility'), ('SECURITY', 'Security & Compliance'), ('DATA_PROTECTION', 'Data Protection & Privacy'), ('DATA_MIGRATION', 'Data Migration & Quality'), ('ACADEMIC_RULES', 'Academic Rules & Business Logic'), ('FINANCE_PAYMENTS', 'Finance & Payments Reconciliation'), ('ROLE_PERMISSIONS', 'Role & Permission Matrix'), ('INSTITUTIONAL_APPROVAL', 'Institutional Approval'), ('INTEGRATIONS', 'Integrations & Third-Party Dependencies'), ('PERFORMANCE', 'Performance & Scalability'), ('BACKUP', 'Backup'), ('DISASTER_RECOVERY', 'Disaster Recovery'), ('BUSINESS_CONTINUITY', 'Business Continuity'), ('MONITORING', 'Monitoring & Observability'), ('UAT', 'User Acceptance Testing'), ('TRAINING', 'Training'), ('DOCUMENTATION', 'Documentation'), ('SUPPORT', 'Support & Helpdesk')], max_length=40)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low / Warning')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('RETESTED', 'Retested'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('description', models.TextField()),
                ('impact', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('evidence_url', models.CharField(blank=True, max_length=500)),
                ('retest_result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golive_issues_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golive_issues_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoLiveReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUNCTIONAL_TESTING', 'Functional Testing'), ('UI_UX', 'UI/UX Quality'), ('ACCESSIBILITY', 'Accessibility'), ('SECURITY', 'Security & Compliance'), ('DATA_PROTECTION', 'Data Protection & Privacy'), ('DATA_MIGRATION', 'Data Migration & Quality'), ('ACADEMIC_RULES', 'Academic Rules & Business Logic'), ('FINANCE_PAYMENTS', 'Finance & Payments Reconciliation'), ('ROLE_PERMISSIONS', 'Role & Permission Matrix'), ('INSTITUTIONAL_APPROVAL', 'Institutional Approval'), ('INTEGRATIONS', 'Integrations & Third-Party Dependencies'), ('PERFORMANCE', 'Performance & Scalability'), ('BACKUP', 'Backup'), ('DISASTER_RECOVERY', 'Disaster Recovery'), ('BUSINESS_CONTINUITY', 'Business Continuity'), ('MONITORING', 'Monitoring & Observability'), ('UAT', 'User Acceptance Testing'), ('TRAINING', 'Training'), ('DOCUMENTATION', 'Documentation'), ('SUPPORT', 'Support & Helpdesk')], max_length=40, unique=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PASS', 'Pass'), ('WARN', 'Warning'), ('FAIL', 'Fail'), ('NOT_APPLICABLE', 'Not Applicable')], default='NOT_STARTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.CharField(blank=True, help_text='Link/reference to the sign-off document, test report, or reconciliation record.', max_length=500)),
                ('signed_off_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The person/office accountable for this area signing off.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
    ]
