# Generated by Django 6.0.5 on 2026-09-10 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0032_semester_system_setup_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='unique_semester_name_per_academic_year'),
        ),
    ]
