# Generated by Django 6.0.5 on 2026-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0033_alter_academicterm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsetting',
            name='disaster_recovery_procedure',
            field=models.TextField(blank=True, default='', help_text='Approved recovery sequence, owners, escalation, and validation steps.'),
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='rpo_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Maximum acceptable data loss window in minutes.'),
        ),
        migrations.AddField(
            model_name='backupsetting',
            name='rto_minutes',
            field=models.PositiveIntegerField(default=120, help_text='Maximum acceptable recovery window in minutes.'),
        ),
    ]
