# Generated by Django 6.0.5 on 2026-09-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_facultyprofile_options_alter_user_role_and_more'),
        ('university', '0035_upgrade_default_admission_letter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentclearance',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='co_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_signed_admission_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='co_signatory_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='co_signatory_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='co_signature_snapshot',
            field=models.FileField(blank=True, null=True, upload_to='signatures/document_snapshots/'),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_admission_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signatory_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signatory_office',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signatory_title',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signature_snapshot',
            field=models.FileField(blank=True, help_text='Immutable snapshot of signature image at issue time', null=True, upload_to='signatures/document_snapshots/'),
        ),
        migrations.AddField(
            model_name='issuedadmissiondocument',
            name='signature_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified'), ('PUBLISH', 'Record Published'), ('UNPUBLISH', 'Record Unpublished'), ('CLOSE', 'Academic Period Closed'), ('REOPEN', 'Academic Period Reopened'), ('SET_CURRENT', 'Set as Current / Active'), ('GENERATE_DOCUMENT', 'Document Generated'), ('REGENERATE_DOCUMENT', 'Document Regenerated'), ('RESEND_DOCUMENT', 'Document Resent'), ('VERIFY_DOCUMENT', 'Document Verified'), ('REVOKE_DOCUMENT', 'Document Revoked'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled'), ('MODULE_STATUS_CHANGE', 'Module Status Changed'), ('SUBMODULE_STATUS_CHANGE', 'Submodule Status Changed'), ('FEATURE_STATUS_CHANGE', 'Feature Status Changed'), ('MODULES_BULK_UPDATE', 'Modules Bulk Status Updated'), ('BACKUP_CREATE', 'Backup Created'), ('BACKUP_RESTORE', 'Backup Restored'), ('BACKUP_VERIFY', 'Backup Verified'), ('BACKUP_DELETE', 'Backup Deleted'), ('BACKUP_SCHEDULE', 'Backup Scheduled'), ('SIGNATURE_UPLOAD', 'Signature Uploaded'), ('SIGNATURE_UPDATE', 'Signature Replaced / Updated'), ('SIGNATURE_REMOVE', 'Signature Removed'), ('SIGNATURE_ACTIVATE', 'Signature Activated'), ('SIGNATURE_DEACTIVATE', 'Signature Deactivated'), ('SIGNATURE_APPROVE', 'Signature Approved'), ('SIGNATURE_REVOKE', 'Signature Revoked'), ('DOCUMENT_SIGNED', 'Document Signed & Finalized'), ('SIGNATORY_CHANGED', 'Document Signatory Changed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Teaching Staff'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Departments', 'Departments'), ('Academics', 'Academics & Registrations'), ('Academic Calendar', 'Academic Years & Semesters'), ('Examinations', 'Examinations & Marks'), ('Fees', 'Fees & Finance'), ('Admissions', 'Admissions & Applications'), ('Timetable', 'Timetable'), ('Security & Auth', 'Security & Authentication'), ('System Configuration', 'System Configuration'), ('Notices & Events', 'Notices & Events'), ('Module Management', 'Module Management'), ('System Backups', 'System Backups & Recovery'), ('Signature Management', 'Signature Management')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.facultyprofile', verbose_name='Teaching Staff'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STUDENT', 'Students'), ('FACULTY', 'Teaching Staff'), ('ADMIN', 'Admins')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='recyclebinitem',
            name='module',
            field=models.CharField(choices=[('Students', 'Students'), ('Faculty', 'Teaching Staff'), ('Courses', 'Courses'), ('Programmes', 'Programmes'), ('Schools', 'Schools & Faculties'), ('Departments', 'Departments'), ('Timetable', 'Timetable Schedules'), ('Fees', 'Fee Invoices & Structures'), ('Admissions', 'Admissions & Applications'), ('Notices', 'Campus Notices'), ('Events', 'Campus Events'), ('Examinations', 'Examinations & Marks'), ('Calendar', 'Academic Calendar & Terms'), ('Other', 'Other Records')], db_index=True, default='Other', max_length=40),
        ),
        migrations.CreateModel(
            name='DocumentSignatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ADMISSION_LETTER', 'Admission Letter'), ('OFFER_LETTER', 'Offer Letter'), ('ACADEMIC_TRANSCRIPT', 'Academic Transcript'), ('PROVISIONAL_TRANSCRIPT', 'Provisional Transcript'), ('EXAM_RESULT_SLIP', 'Examination Result Slip'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('FINANCIAL_STATEMENT', 'Official Financial Statement'), ('DEFERMENT_DECISION', 'Deferment Decision Letter'), ('CLEARANCE_CERTIFICATE', 'Clearance Certificate'), ('OTHER', 'Other Official Document')], max_length=50, unique=True)),
                ('title', models.CharField(help_text='e.g. Official Admission Letter Signatory Policy', max_length=120)),
                ('is_signature_required', models.BooleanField(default=True)),
                ('required_roles', models.CharField(default='ADMIN,REGISTRAR,STAFF', help_text='Comma-separated user roles authorized to sign (e.g. REGISTRAR,STAFF,ADMIN)', max_length=255)),
                ('number_of_signatures', models.PositiveSmallIntegerField(default=1)),
                ('primary_label', models.CharField(default='Registrar (Academic Affairs)', max_length=100)),
                ('primary_position', models.CharField(choices=[('BOTTOM_RIGHT', 'Bottom Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('BOTTOM_CENTER', 'Bottom Center'), ('DUAL_BOTTOM', 'Dual Signatures (Left & Right)')], default='BOTTOM_RIGHT', max_length=30)),
                ('secondary_label', models.CharField(blank=True, default='', help_text='For dual signature documents', max_length=100)),
                ('secondary_position', models.CharField(choices=[('BOTTOM_RIGHT', 'Bottom Right'), ('BOTTOM_LEFT', 'Bottom Left'), ('BOTTOM_CENTER', 'Bottom Center'), ('DUAL_BOTTOM', 'Dual Signatures (Left & Right)')], default='BOTTOM_LEFT', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_users', models.ManyToManyField(blank=True, help_text='Explicitly authorized individuals (leave empty to allow anyone with required role)', related_name='authorized_signature_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
