# Generated by Django 6.0.5 on 2026-09-13 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0037_upgrade_admission_templates_bold_formatting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Guardian Physical / Postal Address'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_alternative_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Guardian Alternative Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_country',
            field=models.CharField(blank=True, default='Kenya', max_length=80, verbose_name='Guardian Country'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guardian Email'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_employer',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Guardian Employer / Organization'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Guardian Full Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_occupation',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Guardian Occupation'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Guardian Primary Phone'),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_relationship',
            field=models.CharField(blank=True, choices=[('Parent', 'Parent'), ('Father', 'Father'), ('Mother', 'Mother'), ('Legal Guardian', 'Legal Guardian'), ('Spouse', 'Spouse'), ('Sibling', 'Sibling'), ('Sponsor', 'Sponsor'), ('Relative', 'Relative'), ('Other', 'Other')], default='Parent', max_length=60, verbose_name='Relationship to Applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_guardian_emergency_contact',
            field=models.BooleanField(default=True, verbose_name='Is Next of Kin / Emergency Contact'),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='applicant_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationfeepayment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_PAYMENT', 'Ready For Payment'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Application Fee Paid'), ('READY_FOR_SUBMISSION', 'Ready For Submission'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted (Admitted)'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled / Matriculated')], db_index=True, default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationfeepayment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('CARD', 'Debit / Credit Card'), ('BANK', 'Bank Transfer'), ('ECITIZEN', 'eCitizen / Government Gateway')], default='MPESA', max_length=15),
        ),
    ]
