# Generated by Django 6.0.5 on 2026-09-13 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0038_application_applicant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMigrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('new_institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('previous_short_name', models.CharField(blank=True, default='', max_length=50)),
                ('new_short_name', models.CharField(blank=True, default='', max_length=50)),
                ('previous_primary_domain', models.CharField(blank=True, default='', max_length=120)),
                ('new_primary_domain', models.CharField(blank=True, default='', max_length=120)),
                ('previous_staff_domain', models.CharField(blank=True, default='', max_length=120)),
                ('new_staff_domain', models.CharField(blank=True, default='', max_length=120)),
                ('previous_student_domain', models.CharField(blank=True, default='', max_length=120)),
                ('new_student_domain', models.CharField(blank=True, default='', max_length=120)),
                ('previous_student_prefix', models.CharField(blank=True, default='students', max_length=50)),
                ('new_student_prefix', models.CharField(blank=True, default='students', max_length=50)),
                ('migration_policy', models.CharField(choices=[('MIGRATE_AND_ARCHIVE_ALIASES', 'Migrate Active Accounts & Retain Old Emails as Aliases'), ('APPLY_TO_NEW_ONLY', 'Apply to New Accounts Only'), ('FULL_REPLACE', 'Full Replacement')], default='MIGRATE_AND_ARCHIVE_ALIASES', max_length=40)),
                ('staff_accounts_affected', models.PositiveIntegerField(default=0)),
                ('student_accounts_affected', models.PositiveIntegerField(default=0)),
                ('total_emails_migrated', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PREVIEW', 'Preview'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('logs', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_migrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Domain Migration Record',
                'verbose_name_plural': 'Domain Migration Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
