# Generated by Django 6.0.5 on 2026-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0039_domainmigrationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmigrationrecord',
            name='new_student_prefix',
            field=models.CharField(blank=True, default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='domainmigrationrecord',
            name='previous_student_prefix',
            field=models.CharField(blank=True, default='student', max_length=50),
        ),
    ]
