# Generated by Django 6.0.5 on 2026-09-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0040_alter_domainmigrationrecord_new_student_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='draft_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dynamic / Extra Draft Payload'),
        ),
        migrations.AddField(
            model_name='application',
            name='draft_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Last Active Form Step'),
        ),
        migrations.AddField(
            model_name='application',
            name='draft_version',
            field=models.PositiveIntegerField(default=1, verbose_name='Draft State Version'),
        ),
        migrations.AddField(
            model_name='application',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='application',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='National ID / Passport No.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='application',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='university.program'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_PAYMENT', 'Ready For Payment'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Application Fee Paid'), ('READY_FOR_SUBMISSION', 'Ready For Submission'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted (Admitted)'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled / Matriculated')], db_index=True, default='DRAFT', max_length=30),
        ),
    ]
