# Generated by Django 6.0.5 on 2026-09-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0041_application_draft_data_application_draft_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('READY_FOR_PAYMENT', 'Ready For Payment'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Application Fee Paid'), ('READY_FOR_SUBMISSION', 'Ready For Submission'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted (Admitted)'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled / Matriculated')], db_index=True, default='SUBMITTED', max_length=30),
        ),
    ]
