# Generated by Django 6.0.5 on 2026-09-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0042_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=80, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='application',
            name='county',
            field=models.CharField(blank=True, default='Nairobi', max_length=80, verbose_name='County / State / Region'),
        ),
        migrations.AddField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Middle / Other Name'),
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=80, verbose_name='Nationality'),
        ),
    ]
