# Generated by Django 6.0.5 on 2026-09-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0043_application_country_application_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfeepayment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('POCHI_LA_BIASHARA', 'Pochi la Biashara'), ('CARD', 'Debit / Credit Card'), ('BANK', 'Bank Transfer'), ('ECITIZEN', 'eCitizen / Government Gateway')], default='MPESA', max_length=30),
        ),
        migrations.AlterField(
            model_name='feeaccount',
            name='account_type',
            field=models.CharField(choices=[('MPESA_PAYBILL', 'M-Pesa Paybill'), ('MPESA_TILL', 'M-Pesa Buy Goods / Till'), ('POCHI_LA_BIASHARA', 'Pochi la Biashara'), ('CARD_GATEWAY', 'Card Payment Gateway'), ('BANK_ACCOUNT', 'Bank Account Transfer'), ('ECITIZEN', 'eCitizen / Government Gateway'), ('OTHER', 'Other Payment Channel')], db_index=True, default='MPESA_PAYBILL', max_length=30),
        ),
        migrations.AlterField(
            model_name='feeaccount',
            name='provider',
            field=models.CharField(choices=[('SAFARICOM', 'Safaricom M-Pesa'), ('STRIPE', 'Stripe'), ('PESAPAL', 'Pesapal'), ('EQUITY', 'Equity Bank'), ('KCB', 'KCB Bank'), ('COOP', 'Co-operative Bank'), ('STANDARD_CHARTERED', 'Standard Chartered'), ('ECITIZEN', 'eCitizen'), ('GENERIC', 'Generic Payment Gateway')], default='SAFARICOM', max_length=40),
        ),
    ]
