# Generated by Django 6.0.5 on 2026-09-13 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0044_alter_applicationfeepayment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('EMAIL_MUTATED', 'Email Address Mutated'), ('DELETE', 'Record Deleted (Soft Delete)'), ('RESTORE', 'Record Restored'), ('PERMANENT_DELETE', 'Record Permanently Purged'), ('IMPORT', 'Data Imported'), ('EXPORT', 'Data Exported'), ('MARKS_SUBMISSION', 'Marks Submitted'), ('MARKS_APPROVAL', 'Marks Approved / Moderated'), ('GRADE_CHANGE', 'Grade Modified'), ('UNIT_REGISTRATION', 'Unit Registration Changed'), ('TRANSCRIPT_GENERATION', 'Transcript Generated'), ('CONFIG_CHANGE', 'System Configuration Modified'), ('PUBLISH', 'Record Published'), ('UNPUBLISH', 'Record Unpublished'), ('CLOSE', 'Academic Period Closed'), ('REOPEN', 'Academic Period Reopened'), ('SET_CURRENT', 'Set as Current / Active'), ('GENERATE_DOCUMENT', 'Document Generated'), ('REGENERATE_DOCUMENT', 'Document Regenerated'), ('RESEND_DOCUMENT', 'Document Resent'), ('VERIFY_DOCUMENT', 'Document Verified'), ('REVOKE_DOCUMENT', 'Document Revoked'), ('MODULE_ENABLE', 'Module Enabled'), ('MODULE_DISABLE', 'Module Disabled'), ('MODULE_STATUS_CHANGE', 'Module Status Changed'), ('SUBMODULE_STATUS_CHANGE', 'Submodule Status Changed'), ('FEATURE_STATUS_CHANGE', 'Feature Status Changed'), ('MODULES_BULK_UPDATE', 'Modules Bulk Status Updated'), ('BACKUP_CREATE', 'Backup Created'), ('BACKUP_RESTORE', 'Backup Restored'), ('BACKUP_VERIFY', 'Backup Verified'), ('BACKUP_DELETE', 'Backup Deleted'), ('BACKUP_SCHEDULE', 'Backup Scheduled'), ('SIGNATURE_UPLOAD', 'Signature Uploaded'), ('SIGNATURE_UPDATE', 'Signature Replaced / Updated'), ('SIGNATURE_REMOVE', 'Signature Removed'), ('SIGNATURE_ACTIVATE', 'Signature Activated'), ('SIGNATURE_DEACTIVATE', 'Signature Deactivated'), ('SIGNATURE_APPROVE', 'Signature Approved'), ('SIGNATURE_REVOKE', 'Signature Revoked'), ('DOCUMENT_SIGNED', 'Document Signed & Finalized'), ('SIGNATORY_CHANGED', 'Document Signatory Changed')], db_index=True, max_length=30),
        ),
        migrations.AddConstraint(
            model_name='applicationfeepayment',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_app_fee_payment_reference'),
        ),
    ]
