# Generated by Django 6.0.5 on 2026-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0048_result_ie_ee_exam_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
