# Generated by Django 6.0.5 on 2026-09-13 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0049_cohort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='current_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='dean_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_published_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='hod_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('MARKING', 'Marks Entry'), ('SUBMITTED', 'Submitted to HoD'), ('HOD_REVIEW', 'Under HoD Review'), ('RETURNED_INSTRUCTOR', 'Returned to Instructor'), ('HOD_APPROVED', 'HoD Approved'), ('DEAN_REVIEW', 'Under Dean Review'), ('RETURNED_HOD', 'Returned to HoD'), ('PUBLISHED', 'Published'), ('UNPUBLISHED', 'Unpublished (Under Review)'), ('CORRECTION', 'Correction Required'), ('RESUBMITTED', 'Resubmitted to HoD'), ('CANCELLED', 'Cancelled'), ('INTERNAL_REVIEW', 'Internal Review'), ('EXTERNAL_REVIEW', 'External Review'), ('APPROVED', 'Approved')], db_index=True, default='DRAFT', max_length=30),
        ),
        migrations.CreateModel(
            name='MarksWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted to HoD'), ('HOD_APPROVE', 'HoD Approved'), ('HOD_SEND_BACK', 'Returned to Instructor by HoD'), ('DEAN_APPROVE', 'Dean Approved'), ('DEAN_SEND_BACK_HOD', 'Returned to HoD by Dean'), ('DEAN_SEND_BACK_INSTRUCTOR', 'Returned to Instructor by Dean'), ('PUBLISH', 'Published by Dean'), ('UNPUBLISH', 'Unpublished'), ('RESUBMIT', 'Resubmitted'), ('REAPPROVE', 'Reapproved'), ('REPUBLISH', 'Republished'), ('CANCEL', 'Cancelled'), ('REOPEN_APPROVED', 'Reopened Approved Marks')], max_length=40)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('actor_role', models.CharField(blank=True, max_length=60)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('reason_category', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('marks_version', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_reference', models.CharField(blank=True, max_length=60)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='university.exam')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MarksVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_versions', to='university.exam')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('exam', 'version_number')},
            },
        ),
    ]
