# Generated by Django 6.0.5 on 2026-09-15 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0052_studenttransferrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffroleassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffroleassignment',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Optional school/faculty scope (e.g. Dean of Faculty of Science)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_role_assignments', to='university.school'),
        ),
        migrations.AlterUniqueTogether(
            name='staffroleassignment',
            unique_together={('user', 'role', 'department', 'school')},
        ),
    ]
