# Generated by Django 6.0.5 on 2026-09-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0053_staffroleassignment_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='supplementary_registration_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='supplementary_registration_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
