# Generated by Django 6.0.5 on 2026-09-15 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0054_academicterm_supplementary_window'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. AUGUST-2026-EXAM', max_length=150)),
                ('study_year', models.PositiveSmallIntegerField(default=1)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('exam_type', models.CharField(choices=[('Regular', 'Regular Examination'), ('Supplementary', 'Supplementary Examination'), ('Special', 'Special Examination'), ('CAT', 'Continuous Assessment (CAT)'), ('Final', 'Final Examination'), ('Retake', 'Retake Examination')], default='Regular', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Scheduled', 'Scheduled'), ('Published', 'Published'), ('Draft', 'Draft')], db_index=True, default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='university.academicyear')),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='university.cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_schedules', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='university.program')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='university.academicterm')),
            ],
            options={
                'ordering': ['-created_at', 'program__code'],
            },
        ),
        migrations.CreateModel(
            name='ExamScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, default='', max_length=120)),
                ('is_core', models.CharField(choices=[('Core', 'Core'), ('Elective', 'Elective')], default='Core', max_length=20)),
                ('is_practical', models.BooleanField(default=False)),
                ('mode_of_exam', models.CharField(choices=[('Physical', 'Physical (On-Campus)'), ('Online', 'Online'), ('Blended', 'Blended')], default='Physical', max_length=20)),
                ('center_name', models.CharField(blank=True, default='ONLINE', max_length=120)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_session', models.CharField(choices=[('Morning', 'Morning (08:30 - 11:30)'), ('Mid-day', 'Mid-day (11:45 - 14:45)'), ('Afternoon', 'Afternoon (15:00 - 18:00)'), ('Evening', 'Evening (18:15 - 20:45)')], default='Morning', max_length=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='university.course')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_item', to='university.exam')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='university.examroom')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='university.examschedule')),
            ],
            options={
                'ordering': ['exam_date', 'course__code'],
            },
        ),
    ]
