# Generated by Django 6.0.5 on 2026-09-15 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0055_examschedule_examscheduleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='senate_approved_at',
            field=models.DateTimeField(blank=True, help_text="When this term's results were ratified by Senate. Gates document release where configured to require it.", null=True),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='senate_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='senate_approved_terms', to=settings.AUTH_USER_MODEL),
        ),
    ]
