# Generated by Django 6.0.5 on 2026-09-16 16:09

import django.core.validators
import university.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0056_academicterm_senate_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='cat_max_marks',
            field=models.DecimalField(decimal_places=2, default=university.models._default_cat_max_marks, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_max_marks',
            field=models.DecimalField(decimal_places=2, default=university.models._default_exam_max_marks, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
