# Generated by Django 6.0.5 on 2026-09-17 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0059_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feereceipt',
            name='cc_email',
            field=models.CharField(blank=True, default='', help_text='Personal application email in CC', max_length=255),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='email_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='fee_receipts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Student primary email address', max_length=254),
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FeeReceiptDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_email', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], db_index=True, default='PENDING', max_length=20)),
                ('trigger', models.CharField(choices=[('AUTO', 'Automatic (Payment Confirmation)'), ('RESEND', 'Manual Resend'), ('RETRY', 'Automatic Retry')], default='AUTO', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_email_deliveries', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='university.feereceipt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
